/**
 * French translations for scenario content - used when window.i18n.currentLang === 'fr'
 * Keys match SCENARIO_CONTENT, SOLUTION_OVERVIEWS, SECTION_CHALLENGES, SCENARIO_SECTION_NAMES, PLACEHOLDER_* structure
 */
(function() {
    window.SCENARIO_CONTENT_FR = {
        'hotels': {
            intro: "Bien que les hôtels n'offrent qu'une hospitalité temporaire, ils s'engagent à créer l'expérience la plus agréable possible pour chaque client. La solution pour les hôtels intègre vidéosurveillance, systèmes d'alarme, affichages vidéo attractifs et une plateforme unifiée pour renforcer la gestion et les niveaux de sécurité.",
            sections: [
                { title: "Parking", challenges: "Les parkings d'hôtels font souvent face à des opérations inefficaces aux heures de pointe. Les clients ont parfois du mal à trouver des places disponibles.", challengeImg1: "Efficacité aux heures de pointe", challengeImg2: "Trouver des places disponibles", whatWeOffer: "Entrée et sortie sans arrêt, règles de stationnement flexibles, enregistrements de véhicules consultables. Caméras de guidage pour un parking efficace.", benefits: [{ title: "Entrée et sortie", items: ["Efficacité accrue via les statistiques", "Collecte de preuves simplifiée", "Sortie de véhicules sécurisée"] }, { title: "Guidage parking", items: ["Localiser rapidement le véhicule garé", "Meilleure efficacité aux heures de pointe"] }], features: ["Reconnaissance floue des plaques", "Comptage de véhicules", "Inscription en libre-service", "Indications lumineuses multicolores"] },
                { title: "Hall d'accueil", challenges: "Grande affluence et activité 24h/24. Protection de sécurité constante nécessaire. Alertes précoces et réponse rapide essentielles.", challengeImg1: "Protection des grands espaces", challengeImg2: "Consultation des enregistrements", whatWeOffer: "Vidéosurveillance professionnelle à couverture large. Affichages commerciaux pour l'accueil et la publicité.", benefits: [{ title: "Sécurité vidéo", items: ["Alertes instantanées avec lumière et son", "Réduction des fausses alarmes", "Couverture des grands espaces"] }, { title: "Publicité", items: ["Diffusion rapide de contenu", "Affichage de contenu professionnel"] }], features: ["Imagerie couleur 24h/24", "Champ de vision 180°", "Formats multimédias variés", "Programmes flexibles"] },
                { title: "Réception", challenges: "Réponses rapides et expérience client. Prévenir erreurs de transaction et vols. Éviter les longues files d'attente.", challengeImg1: "Service retardé", challengeImg2: "Longue attente", whatWeOffer: "Vidéosurveillance IA avec gestion des files, capteurs d'alarme sans fil et boutons de panique.", benefits: [{ title: "Efficacité du service", items: ["Bouton de panique pour urgences", "Gestion des files pour le déploiement du personnel"] }], features: ["Alarme bouton de panique", "Capteurs d'alarme sans fil", "Statistiques de file multicaméra", "Vidéo HD, détection de file IA"] },
                { title: "Espaces intérieurs publics", challenges: "Sécurité 24h/24 pour salles d'événements, couloirs, bars, restaurants, salles de sport, piscines. Vidéo nette, couverture large, alertes précoces.", challengeImg1: "Espaces divers", challengeImg2: "Réponse d'urgence", whatWeOffer: "Variété de vidéosurveillance pour une vidéo nette 24h/24. Alarme sans fil facile à déployer.", benefits: [{ title: "Sécurité vidéo", items: ["Coûts d'installation réduits", "Protection fiable 24h/24"] }], features: ["Mode couloir", "Panoramique 180° / 360°", "Excellente basse luminosité", "Pont sans fil pour ascenseurs"] },
                { title: "Salles de réunion", challenges: "Affichage et partage de contenu pratiques. Voix claire pour la collaboration. Mise en œuvre rapide de la visioconférence.", challengeImg1: "Affichage et projection", challengeImg2: "Partage de contenu", whatWeOffer: "Écrans plats interactifs avec caméra HD et haut-parleur pour visioconférence professionnelle et collaboration locale.", benefits: [{ title: "Visioconférence", items: ["Vidéo HD, audio clair", "Compatible Zoom, Webex"] }, { title: "Collaboration", items: ["Projection sans câble", "Télécommande et installation par lot"] }], features: ["Caméra intégrée ou USB", "Projection sans fil", "Tableau blanc", "Installation .apk par lot"] },
                { title: "Inventaire", challenges: "La gestion des stocks doit prévenir les pertes et dégâts dus aux intrus, vols internes et dangers. Alertes précoces et récupération de preuves.", challengeImg1: "Perte et dégâts d'inventaire", challengeImg2: "Réponse d'urgence retardée", whatWeOffer: "Accès sans contact et réservé au personnel avec vérification vidéo. Alarmes de température et capteurs sans fil.", benefits: [{ title: "Accès et vérification", items: ["Accès reconnaissance faciale sans contact", "Vérification vidéo pour les incidents", "Pré-alertes incendie et menaces"] }], features: ["Vérifications vidéo température, intrusion, accès", "Détecteurs d'alarme sans fil", "Alarme anomalie température"] },
                { title: "Périmètre", challenges: "Hôtels en ville : forte affluence. Banlieues : faible luminosité la nuit. Vidéo nette et détection d'intrusion jour et nuit.", challengeImg1: "Réponse d'urgence", challengeImg2: "Consultation des enregistrements", whatWeOffer: "Vidéo panoramique, imagerie couleur 24h/24. Recherche post-événement IA avec filtres pour localiser les cibles.", benefits: [{ title: "Détection", items: ["Alerte instantanée avec lumière et son", "Réduction des fausses alarmes", "Nette 24h/24"] }], features: ["Lumière et son intégrés", "Réduction fausses alarmes IA", "Analyse des attributs", "Vue panoramique"] },
                { title: "Salle de contrôle", challenges: "Combinaison complexe de sous-systèmes. Visibilité limitée entre applications. Maintenance difficile double la charge de travail.", challengeImg1: "Personnel limité", challengeImg2: "Maintenance informatique complexe", whatWeOffer: "Plateforme tout-en-un pour surveillance, traitement des incidents, contrôle à distance, preuves et maintenance.", benefits: [{ title: "Gestion unifiée", items: ["Panneau de visualisation par rôle", "Interopérabilité multi-systèmes"] }], features: ["Tableaux de bord santé système", "Récupération et archivage des enregistrements", "Pop-up d'alarme auto", "Murs vidéo 4K"] }
            ]
        },
        'factories': {
            intro: "L'usine est une synthèse de personnel, actifs, équipements et machines. Des défis complexes surviennent fréquemment. La solution par scénario de Synergates pour les usines offre des moyens rentables de garantir une production efficace et sûre, ainsi qu'une protection des biens.",
            sections: [
                { title: "Entrée et sortie véhicules", challenges: "Le contrôle manuel d'identité des conducteurs et véhicules peut être inconfortable et chronophage, ainsi que difficile à retracer pour l'enquête sur les incidents.", challengeImg1: "Congestion aux heures de pointe", challengeImg2: "Difficulté à retrouver les enregistrements", whatWeOffer: "Efficacité et sécurité accrues pour la gestion des véhicules via authentification ANPR sans contact, passage en voiture et enregistrements faciles à consulter.", benefits: [{ title: "Sortie véhicules sécurisée et efficace", items: ["Alarme liste noire / notification VIP", "Passage authentifié sans arrêt"] }, { title: "Efficacité opérationnelle", items: ["Alarme pour véhicule en liste noire et parking complet", "Enregistrements via reconnaissance floue des plaques"] }], features: ["Affichage LED des places et infos parking", "Enregistrements et rapports statistiques", "Contrôle d'accès distant par interphonie vidéo", "Accès véhicule par ANPR ou badge"] },
                { title: "Hall d'entrée", challenges: "Les usines sont souvent très réglementées pour la sécurité du lieu et du personnel. La réception à l'entrée doit gérer efficacement les visiteurs avec des autorisations d'accès sécurisées et des capacités de mise à jour et de consultation.", challengeImg1: "Difficile de gérer le statut des visiteurs sur site", challengeImg2: "Difficile de retracer les dossiers papier", whatWeOffer: "Sécurité au travail et efficacité opérationnelle grâce à la vidéosurveillance professionnelle et à une gestion des visiteurs numérisée.", benefits: [{ title: "Gestion des visiteurs sans papier", items: ["Protection de la vie privée via suppression auto", "Recherche et export de rapports", "Vue rapide de tous les statuts visiteurs"] }, { title: "Autorisation d'accès synchronisée", items: ["Check-out manuel ou libre-service", "Permission en un clic vers groupes d'accès"] }], features: ["Suppression auto configurable des enregistrements", "Recherche et export des enregistrements visiteurs", "Inscription, badge, check-in/out"] },
                { title: "Atelier", challenges: "Assurer la continuité de production exige de gérer un grand groupe d'employés avec quarts multiples, plannings complexes et forte rotation.", challengeImg1: "Menaces à la continuité de production", challengeImg2: "Faible efficacité aux heures de pointe", whatWeOffer: "Efficacité, authenticité et visibilité accrues pour l'accès et la gestion des présences.", benefits: [{ title: "Efficacité et fiabilité", items: ["Anti-usurpation IA", "Authentification sans contact, pas de badge physique"] }, { title: "Modes d'authentification variés", items: ["Visage, badge et empreinte dans une unité", "Adapté aux cas d'usage courants"] }], features: ["Vidéosurveillance HD intérieur", "Accès et présence par reconnaissance IA, badge, empreinte", "Vérification vidéo des enregistrements", "Règles de quarts et plannings flexibles"] },
                { title: "Entrepôt", challenges: "Les rôles principaux du personnel de sécurité entrepôt incluent la prévention des pertes et dégâts dus aux intrus, vols internes, accidents et dangers.", challengeImg1: "Vol et vandalisme", challengeImg2: "Dégâts dus aux dangers", whatWeOffer: "Alarme d'intrusion, alarme anomalie température, contrôle d'accès IA et vidéo HD 24h/24 sur une plateforme unique.", benefits: [{ title: "Déploiement simple, fonctionnalités étendues", items: ["Multi-lentilles, mini PTZ, fisheye pour vidéo HD large zone", "Imagerie thermique avec alarme température et vidéo optique HD"] }, { title: "Prévention des pertes renforcée", items: ["Alarme push instantanée avec vidéo HD", "Détection température pour risques incendie"] }], features: ["Alarme anomalie température", "Vidéo HD large zone 24h/24", "Vérification vidéo des alarmes", "Alarme sans fil, installation facile"] },
                { title: "Périmètre", challenges: "Les périmètres d'usine ont souvent un éclairage nocturne limité. Les équipes de sécurité doivent distinguer rapidement les humains ou véhicules des objets inoffensifs.", challengeImg1: "Lumière faible et fausses alarmes", challengeImg2: "Réponse et dissuasion rapides", whatWeOffer: "Protection du périmètre avec minimum de fausses alarmes via vidéo 24h/24, toutes conditions, IA.", benefits: [{ title: "Détails visuels plus nets", items: ["Thermographie adaptable à la météo", "Vidéo HD couleur 24h/24", "Moins de fausses alarmes"] }, { title: "Gestion d'incidents plus efficace", items: ["Éclairage et audio sur site", "Découverte et notification anticipées"] }], features: ["Alarme lumière et son sur site", "Filtre fausses alarmes IA humains et véhicules", "Vidéo nette 24h/24 toutes conditions"] },
                { title: "Salle de contrôle", challenges: "Les salles de contrôle combinent plusieurs fonctions avec divers sous-systèmes. La visibilité limitée peut doubler la charge de travail.", challengeImg1: "Personnel limité, divers sous-systèmes", challengeImg2: "Maintenance informatique complexe", whatWeOffer: "Tous les sous-systèmes unifiés sur une plateforme pour surveillance, gestion d'incidents et maintenance.", benefits: [{ title: "Déploiement léger, fonctionnement unifié", items: ["Tous les sous-systèmes sur une plateforme", "Exigences minimales : i3, 8 Go RAM", "Disposition personnalisable des caméras"] }, { title: "Statut système rapide", items: ["Schéma, rapports et topologie réseau", "Stockage périphérique ou central"] }], features: ["Gestion centralisée vidéo, accès, véhicules, alarme, présence", "Tableau de bord santé", "Stockage périphérique/central", "Murs vidéo haute clarté"] }
            ]
        },
        'offices': {
            intro: "Les bâtiments de bureaux nécessitent une sécurité fluide, un contrôle d'accès et une efficacité opérationnelle. Notre solution par scénario intègre gestion des véhicules, accueil des visiteurs, sécurité intérieure et plateforme de contrôle unifiée.",
            sections: [
                { title: "Entrée et sortie véhicules", challenges: "Le contrôle manuel des conducteurs et véhicules peut être inconfortable et difficile à retracer lors de la recherche d'enregistrements spécifiques.", challengeImg1: "Congestion aux heures de pointe", challengeImg2: "Difficulté à retrouver les enregistrements", whatWeOffer: "Authentification ANPR sans contact et enregistrements de véhicules faciles à consulter pour une entrée et sortie sécurisée sans arrêt.", benefits: [{ title: "Efficacité", items: ["Alarme liste noire et notification VIP", "Authentification au passage"] }, { title: "Enregistrements", items: ["Recherche floue par plaque", "Statistiques et rapports parking"] }], features: ["Accès ANPR ou par badge", "Enregistrements véhicules", "Interphonie vidéo", "Affichage LED des places disponibles"] },
                { title: "Entrées porte", challenges: "Les entrées multiples nécessitent un accès sécurisé et traçable sans créer des goulots d'étranglement aux heures de pointe.", challengeImg1: "Flux aux heures de pointe", challengeImg2: "Traçabilité de l'accès", whatWeOffer: "Authentification multi-mode et autorisations d'accès synchronisées entre portes et ascenseurs.", benefits: [{ title: "Contrôle d'accès", items: ["Visage, badge, empreinte en une unité", "Anti-usurpation IA"] }, { title: "Visibilité", items: ["Vérification vidéo des événements d'accès", "Statut centralisé des portes"] }], features: ["Authentification sans contact", "Règles de quarts flexibles", "Vidéosurveillance HD aux entrées", "Enregistrements d'accès"] },
                { title: "Réception", challenges: "La réception doit gérer les visiteurs efficacement avec des autorisations d'accès sécurisées et une mise à jour et consultation faciles.", challengeImg1: "Statut des visiteurs", challengeImg2: "Consultation des enregistrements", whatWeOffer: "Gestion des visiteurs numérisée avec autorisations d'accès synchronisées aux portes et ascenseurs assignés.", benefits: [{ title: "Gestion des visiteurs", items: ["Recherche et export faciles", "Permission en un clic vers groupes d'accès"] }, { title: "Confidentialité", items: ["Suppression auto configurable", "Check-out manuel ou libre-service"] }], features: ["Inscription visiteurs", "Impression badges", "Check-in/out", "Niveaux d'accès pré-assignés"] },
                { title: "Espaces publics intérieurs", challenges: "Les couloirs, atriums et espaces communs nécessitent une vidéo nette 24h/24, une couverture large et des alertes précoces.", challengeImg1: "Couverture des grands espaces", challengeImg2: "Réponse d'urgence", whatWeOffer: "Vidéosurveillance professionnelle à couverture large et réduction des fausses alarmes pour les espaces publics.", benefits: [{ title: "Sécurité vidéo", items: ["Alertes instantanées avec lumière et son", "Couverture large", "Réduction des fausses alarmes"] }], features: ["Imagerie couleur 24h/24", "Champ de vision 180°", "Mode couloir", "Excellente basse luminosité"] },
                { title: "Salles de réunion", challenges: "Affichage et partage de contenu pratiques, voix claire pour la collaboration, visioconférence rapide.", challengeImg1: "Affichage et partage", challengeImg2: "Visioconférence", whatWeOffer: "Écrans plats interactifs avec caméra HD et haut-parleur pour visioconférence professionnelle.", benefits: [{ title: "Visioconférence", items: ["Vidéo HD, audio clair", "Compatible Zoom, Webex"] }, { title: "Collaboration", items: ["Projection sans câble", "Télécommande et installation par lot"] }], features: ["Caméra intégrée ou USB", "Projection sans fil", "Tableau blanc", "Installation .apk par lot"] },
                { title: "Inventaire", challenges: "Prévenir les pertes et dégâts dus aux intrus, vols internes et dangers ; alertes précoces et récupération de preuves.", challengeImg1: "Pertes d'inventaire", challengeImg2: "Réponse retardée", whatWeOffer: "Accès sans contact avec vérification vidéo, alarmes anomalie température et capteurs sans fil.", benefits: [{ title: "Accès et vérification", items: ["Reconnaissance faciale sans contact", "Vérification vidéo pour incidents", "Pré-alertes incendie et menaces"] }], features: ["Vérification vidéo température, intrusion, accès", "Détecteurs d'alarme sans fil", "Alarme anomalie température"] },
                { title: "Périmètre", challenges: "Les périmètres de bâtiments nécessitent une vidéo nette et une détection d'intrusion précise jour et nuit.", challengeImg1: "Visibilité nocturne", challengeImg2: "Détection d'intrusion", whatWeOffer: "Imagerie couleur 24h/24 et recherche post-événement IA pour localiser rapidement les cibles.", benefits: [{ title: "Détection", items: ["Alerte instantanée avec lumière et son", "Réduction des fausses alarmes", "Nette 24h/24"] }], features: ["Lumière et son intégrés", "Réduction fausses alarmes IA", "Analyse des attributs", "Vue panoramique"] },
                { title: "Salle de contrôle", challenges: "Plusieurs sous-systèmes avec visibilité limitée entre applications et maintenance difficile.", challengeImg1: "Personnel limité", challengeImg2: "Informatique complexe", whatWeOffer: "Tous les sous-systèmes unifiés sur une plateforme pour surveillance, gestion d'incidents et maintenance.", benefits: [{ title: "Gestion unifiée", items: ["Panneau personnalisé par rôle", "Tous les sous-systèmes sur une plateforme"] }, { title: "Statut", items: ["Tableau de bord santé système", "Rapports et topologie visualisés"] }], features: ["Centralisé vidéo, accès, véhicules, alarme, présence", "Tableau de bord santé", "Stockage périphérique/central", "Murs vidéo 4K"] }
            ]
        },
        'construction-site': {
            intro: "Les chantiers font face à de nombreux défis complexes. Notre solution propose des systèmes diversifiés et faciles à déployer pour une sécurité et une protection efficaces.",
            sections: [
                { title: "Entrée et sortie véhicules", challenges: "Contrôle d'identité manuel inconfortable et difficile à retracer.", challengeImg1: "Congestion aux heures de pointe", challengeImg2: "Difficulté à retrouver les enregistrements", whatWeOffer: "Entrée et sortie fluides avec ANPR. Consultation facile des enregistrements véhicules.", benefits: [{ title: "Efficacité", items: ["Gestion temporaire des véhicules", "Enregistrements vidéo"] }], features: ["Appel centre distant", "Alarmes liste noire", "Authentification véhicule"] },
                { title: "Entrée principale", challenges: "Accès sécurisé pour travailleurs et visiteurs. Enregistrements de présence fiables.", challengeImg1: "Heures de pointe", challengeImg2: "Litiges de présence", whatWeOffer: "Accès et présence avec authentification et visibilité.", benefits: [{ title: "Accès", items: ["Vérification visuelle", "Divers modes d'authentification"] }], features: ["Quarts flexibles", "Anti-usurpation IA", "Sécurité vidéo"] },
                { title: "Zones de construction", challenges: "Lumière faible la nuit. Surveillance claire et détection d'intrusion.", challengeImg1: "Éclairage faible", challengeImg2: "Progression", whatWeOffer: "Vidéos en time-lapse montrant la progression des travaux.", benefits: [{ title: "Progression", items: ["Conception environnement difficile", "Affichage clair de la progression"] }], features: ["Résistant aux intempéries", "Enregistrement time-lapse", "Vidéo HD"] },
                { title: "Zones clés", challenges: "Risques comme incendie et vol. Réponse rapide nécessaire.", challengeImg1: "Risques incendie", challengeImg2: "Intrusion", whatWeOffer: "Vidéo grand angle, imagerie couleur 24h/24, imagerie thermographique.", benefits: [{ title: "Protection", items: ["Fiable par toute lumière", "Alertes incendie précoces"] }], features: ["Anomalie température", "AcuSense", "Caméra thermographique"] },
                { title: "Grues à tour", challenges: "Difficultés de câblage, vibration, éclairage faible. Sécurité opérationnelle et preuves HD.", challengeImg1: "Environnements difficiles", challengeImg2: "Supervision", whatWeOffer: "Produits faciles à déployer pour espaces étroits et environnements difficiles.", benefits: [{ title: "Sécurité", items: ["Sécurité de production", "Imagerie vidéo stable"] }], features: ["Stabilisation d'image", "Caméra anti-vibration", "Transmission sans fil"] },
                { title: "Bureau de gestion", challenges: "Plusieurs sous-systèmes. Visibilité limitée double la charge de travail.", challengeImg1: "Personnel limité", challengeImg2: "Informatique complexe", whatWeOffer: "Gestion unifiée sur une plateforme.", benefits: [{ title: "Efficacité", items: ["Interface personnalisable", "Gestion centralisée"] }], features: ["Tableau de bord santé", "Stockage périphérique/central", "Murs vidéo"] }
            ]
        },
        'gas-stations': {
            intro: "Les stations-service nécessitent une sécurité 24h/24 sur les zones de ravitaillement, le magasin et les bureaux. Notre solution couvre le flux véhicules, la sécurité du ravitaillement, le déchargement, les entrées du magasin, les zones d'achat, la caisse et les bureaux du personnel.",
            sections: [
                { title: "Entrée et sortie véhicules", challenges: "Gérer le flux véhicules et prévenir les accès non autorisés tout en gardant la circulation fluide.", challengeImg1: "Flux véhicules", challengeImg2: "Contrôle d'accès", whatWeOffer: "ANPR et contrôle d'accès pour authentification véhicule sans contact et enregistrements consultables.", benefits: [{ title: "Efficacité", items: ["Passage sans arrêt", "Alarme liste noire"] }, { title: "Enregistrements", items: ["Recherche floue par plaque", "Enregistrements véhicules et horaires"] }], features: ["ANPR ou barrière", "Enregistrements véhicules", "Affichage LED", "Interphonie vidéo"] },
                { title: "Zones de ravitaillement", challenges: "Surveillance de l'activité de ravitaillement pour sécurité, prévention du vol et preuves claires en cas d'incident.", challengeImg1: "Sécurité ravitaillement", challengeImg2: "Preuves d'incident", whatWeOffer: "Couverture vidéo HD des pompes et de l'avant-cour avec imagerie couleur 24h/24 et analytics optionnels.", benefits: [{ title: "Sécurité", items: ["Vidéo avant-cour claire", "Alerte instantanée sur anomalies"] }, { title: "Preuves", items: ["Consultation par heure et zone", "Couverture large avec moins de caméras"] }], features: ["Champ large et basse luminosité", "Design antivandalisme", "Audio pour dissuasion", "Intégration gestion carburant"] },
                { title: "Zone de déchargement", challenges: "Sécuriser les zones de livraison et déchargement contre vol et accès non autorisé.", challengeImg1: "Sécurité livraison", challengeImg2: "Enregistrements déchargement", whatWeOffer: "Accès contrôlé et couverture vidéo complète des zones de déchargement avec enregistrement par événement.", benefits: [{ title: "Sécurité", items: ["Contrôle d'accès pour livreurs", "Vérification vidéo des livraisons"] }, { title: "Audit", items: ["Enregistrements horodatés", "Intégration inventaire"] }], features: ["Contrôle d'accès", "Vidéosurveillance HD", "Détection mouvement et intrusion", "Visibilité nocturne"] },
                { title: "Entrées du magasin", challenges: "Équilibre entre accès ouvert aux clients et prévention du vol avec visibilité claire entrée/sortie.", challengeImg1: "Flux clients", challengeImg2: "Prévention du vol", whatWeOffer: "Analytics vidéo aux entrées avec comptage personnes et détection de flânerie.", benefits: [{ title: "Visibilité", items: ["Vidéo entrée/sortie claire", "Surveillance heures de pointe"] }, { title: "Prévention", items: ["Dissuasion par caméras visibles", "Consultation rapide des preuves"] }], features: ["Caméras entrée HD", "Comptage personnes optionnel", "Basse luminosité", "Champ large"] },
                { title: "Zones d'achat", challenges: "Sécurité en magasin sans gêner l'expérience d'achat ; dissuasion et preuves.", challengeImg1: "Sécurité en magasin", challengeImg2: "Récupération de preuves", whatWeOffer: "Couverture discrète mais efficace avec analytics pour zones chaudes et temps de séjour.", benefits: [{ title: "Dissuasion", items: ["Couverture visible dans les allées clés", "Avertissement audio optionnel"] }, { title: "Insights", items: ["Cartes thermiques et analytics de séjour", "Intégration caisse si besoin"] }], features: ["Caméras intérieur HD", "Options fisheye et dôme", "Analytics", "Visualisation à distance"] },
                { title: "Comptoir de caisse", challenges: "Prévenir vol à la caisse et litiges ; vue claire des transactions et gestion des files.", challengeImg1: "Sécurité caisse", challengeImg2: "Gestion des files", whatWeOffer: "Couverture ciblée de la caisse avec longueur de file et intégration alarme panique.", benefits: [{ title: "Sécurité transaction", items: ["Vue claire espèces et carte", "Bouton panique pour urgences"] }, { title: "Opérations", items: ["Statistiques de file pour déploiement personnel", "Preuves pour litiges"] }], features: ["Couverture caisse HD", "Intégration bouton panique", "Analytics file", "Superposition caisse optionnelle"] },
                { title: "Bureau du personnel", challenges: "Sécuriser les bureaux et la manipulation d'espèces avec contrôle d'accès et piste d'audit.", challengeImg1: "Sécurité bureau", challengeImg2: "Manipulation espèces", whatWeOffer: "Contrôle d'accès et vidéo pour zones réservées au personnel avec permissions synchronisées.", benefits: [{ title: "Accès", items: ["Accès restreint par rôle", "Règles d'escorte visiteurs"] }, { title: "Audit", items: ["Enregistrements accès et vidéo", "Intégration alarme"] }], features: ["Contrôle d'accès", "Vidéosurveillance HD", "Vérification vidéo", "Intégration alarme"] }
            ]
        },
        'schools': {
            intro: "Les écoles et campus ont besoin d'un flux véhicules et piétons sûr, de périmètres sécurisés et de visibilité dans les espaces publics et les salles de classe. Notre solution couvre les entrées, portails, dortoirs, espaces publics, périmètre, salles de classe et salle de contrôle.",
            sections: [
                { title: "Entrée et sortie véhicules", challenges: "Gérer les véhicules des parents et du personnel tout en gardant les zones élèves sûres et les enregistrements traçables.", challengeImg1: "Flux véhicules", challengeImg2: "Consultation des enregistrements", whatWeOffer: "ANPR et contrôle d'accès pour véhicules autorisés avec enregistrements clairs et pré-inscription des visiteurs.", benefits: [{ title: "Sécurité", items: ["Liste noire et blanche", "Flux sans arrêt pour véhicules autorisés"] }, { title: "Enregistrements", items: ["Recherche floue plaque", "Logs horaires et visiteurs"] }], features: ["ANPR", "Contrôle barrière", "Enregistrements véhicules", "Interphonie vidéo"] },
                { title: "Portails et dortoirs", challenges: "Contrôler qui entre dans le campus et les dortoirs avec authentification fiable et gestion des visiteurs.", challengeImg1: "Accès portail", challengeImg2: "Sécurité dortoir", whatWeOffer: "Contrôle d'accès aux portails et entrées dortoirs avec visage, badge ou empreinte et badgeage visiteurs.", benefits: [{ title: "Accès", items: ["Authentification multi-mode", "Anti-usurpation"] }, { title: "Visiteurs", items: ["Pré-inscription et badge", "Escorte et limites de temps"] }], features: ["Portails et tourniquets", "Gestion des visiteurs", "Vidéosurveillance HD", "Enregistrements d'accès"] },
                { title: "Espace public", challenges: "Les couloirs, cafétérias et espaces extérieurs nécessitent une visibilité 24h/24 et une réponse rapide aux incidents.", challengeImg1: "Espaces communs", challengeImg2: "Réponse aux incidents", whatWeOffer: "Vidéo grand angle et couloir avec alertes instantanées et réduction des fausses alarmes.", benefits: [{ title: "Visibilité", items: ["Champ large et couleur 24h/24", "Couverture couloir et extérieur"] }, { title: "Réponse", items: ["Alerte lumière et son instantanée", "Consultation facile des preuves"] }], features: ["Options 180° / 360°", "Basse luminosité", "Audio dissuasion", "Recherche événement"] },
                { title: "Périmètre", challenges: "Protection du périmètre du campus avec minimum de fausses alarmes et visibilité nocturne claire.", challengeImg1: "Intrusion périmètre", challengeImg2: "Visibilité nocturne", whatWeOffer: "Vidéo périmètre 24h/24 IA avec dissuasion sur site et alarmes push automatiques.", benefits: [{ title: "Détection", items: ["Filtre humains et véhicules", "Réduction des fausses alarmes"] }, { title: "Dissuasion", items: ["Lumière et son sur site", "Notification précoce"] }], features: ["Options thermique et optique", "Filtre fausses alarmes IA", "Alarme lumière et son", "Toutes conditions"] },
                { title: "Salle de classe", challenges: "Soutien sécurité et conscience de la situation sans perturber l'enseignement.", challengeImg1: "Sécurité salle", challengeImg2: "Conscience de la situation", whatWeOffer: "Couverture discrète des salles avec options de confidentialité et intégration protocoles d'urgence.", benefits: [{ title: "Sécurité", items: ["Vidéo claire pour urgences", "Déploiement conforme confidentialité"] }, { title: "Opérations", items: ["Visualisation à distance admin", "Preuves pour incidents"] }], features: ["Caméras intérieur HD", "Masquage de confidentialité", "Intégration urgence", "Option audio"] },
                { title: "Salle de contrôle", challenges: "Unifier vidéo, accès, alarme et systèmes d'urgence pour un personnel limité.", challengeImg1: "Systèmes multiples", challengeImg2: "Efficacité du personnel", whatWeOffer: "Une plateforme pour tous les sous-systèmes de sécurité avec dispositions personnalisables et surveillance santé.", benefits: [{ title: "Fonctionnement unifié", items: ["Une plateforme", "Disposition personnalisable"] }, { title: "Fiabilité", items: ["Tableau de bord santé", "Options stockage et sauvegarde"] }], features: ["Gestion centralisée", "Tableau de bord santé", "Murs vidéo", "Intégration alarme et accès"] }
            ]
        },
        'warehouses': {
            intro: "Les entrepôts ont besoin d'une visibilité de bout en bout : sécurité générale, gestion des quais, suivi des colis et flux de circulation. Notre solution intègre vidéo, contrôle d'accès et analytics sur une plateforme unique.",
            sections: [
                { title: "Sécurité générale", challenges: "Prévenir les pertes dues aux intrus, vols internes et dangers ; alertes précoces et récupération de preuves.", challengeImg1: "Vol et intrusion", challengeImg2: "Dangers", whatWeOffer: "Vidéo HD 24h/24, alarmes d'intrusion et de température, et contrôle d'accès IA sur une plateforme unique.", benefits: [{ title: "Conscience de la situation", items: ["Conscience de situation multidimensionnelle", "Alarmes température et intrusion"] }, { title: "Preuves", items: ["Alarme push avec vidéo HD", "Consultation par heure et zone"] }], features: ["Vidéo HD grand angle", "Alarme anomalie température", "Alarme sans fil", "Vérification vidéo"] },
                { title: "Gestion des quais", challenges: "Gérer les quais de chargement pour sécurité, utilisation des emplacements et enregistrements clairs des arrivées et départs.", challengeImg1: "Sécurité quais", challengeImg2: "Utilisation des emplacements", whatWeOffer: "Vidéo et contrôle d'accès ciblés quais avec réservation d'emplacements et identification véhicules.", benefits: [{ title: "Sécurité", items: ["Vue claire de l'activité quais", "Alertes accès non autorisé"] }, { title: "Efficacité", items: ["Statut quais en un coup d'œil", "Enregistrements pour planification"] }], features: ["Caméras quais", "Contrôle d'accès aux quais", "Option ANPR", "Intégration WMS"] },
                { title: "Suivi des colis", challenges: "Suivi des colis et paquets de la réception au staging et à l'expédition avec piste d'audit.", challengeImg1: "Flux des colis", challengeImg2: "Piste d'audit", whatWeOffer: "Vidéo et intégration code-barres/scan pour mouvement des colis et preuve de remise.", benefits: [{ title: "Traçabilité", items: ["Vidéo horodatée aux points clés", "Preuve de réception et d'expédition"] }, { title: "Litiges", items: ["Consultation rapide des preuves", "Moins de pertes et litiges"] }], features: ["HD à réception et expédition", "Intégration scan", "Enregistrement par événement", "Recherche par heure et zone"] },
                { title: "Gestion du trafic", challenges: "Gérer le trafic interne des chariots et véhicules pour éviter congestion et accidents.", challengeImg1: "Trafic interne", challengeImg2: "Congestion et sécurité", whatWeOffer: "Analytics vidéo pour flux du trafic, règles de vitesse et de zone, intégration accès et alarme.", benefits: [{ title: "Sécurité", items: ["Analytics zone et vitesse", "Preuves incidents et quasi-accidents"] }, { title: "Flux", items: ["Visibilité congestion et zones chaudes", "Meilleure disposition et itinéraires"] }], features: ["Analytics trafic et zones", "Détection chariots et véhicules", "Couverture HD des allées et croisements", "Plateforme unifiée"] }
            ]
        }
    };

    window.SOLUTION_OVERVIEWS_FR = {
        'classroom-hub': "La numérisation de l'éducation est en constante évolution. Les élèves grandissant dans un monde technologique attendent un apprentissage plus immersif et de meilleures ressources. Notre solution Classroom Hub étend les salles réelles aux salles numériques et virtuelles.",
        'urban-roadways': "Les communautés urbaines dépendent des routes pour déplacer personnes et véhicules. Avec une fréquence élevée, les routes urbaines font face à la congestion, aux infractions (feu rouge, excès de vitesse, stationnement illégal) avec une surveillance limitée.",
        'stores': "Les magasins font face chaque jour à des défis de prévention des pertes et d'efficacité opérationnelle. Notre solution combine une vidéosurveillance fiable avec des analytics pour soutenir la gestion quotidienne.",
        'bus-stop': "La croissance des villes et l'extension des routes exigent des transports en commun améliorés. Notre solution Bus Stop utilise l'analytique IA, la vidéosurveillance et une gestion centralisée.",
        'car-dealerships': "Les concessions automobiles regroupent ventes, service et pièces. Avec de nombreuses voitures de valeur exposées, la sécurité est complexe et critique.",
        'conference-rooms': "La visioconférence est devenue essentielle. Notre solution supporte les petites à grandes conférences de manière rentable.",
        'electrical-substations': "Les postes électriques jouent un rôle clé dans la transmission d'énergie. Synergates fournit une protection de sécurité fiable.",
        'highways': "Les autoroutes transportent des milliers de véhicules quotidiennement. Notre solution couvre péages, voies, rampes, tunnels et centres de commande.",
        'monitoring-center': "Les centres de monitoring ont besoin d'une solution d'affichage et de contrôle efficace. Synergates propose des solutions professionnelles.",
        'parking-lots': "Les opérateurs de parkings visent une utilisation économique de l'espace. Notre solution guide les conducteurs vers les places disponibles.",
        'shopping-malls': "Le vol à l'étalage et les budgets serrés challengent les centres commerciaux. Notre solution aide à attirer et satisfaire un public plus large.",
        'transit-bus-onboard': "Les bus urbains font face à des préoccupations de sécurité et d'expérience passagers. Notre solution aide les opérateurs à gérer de manière globale.",
        'onshore-oilfields': "Les champs pétroliers onshore sont une source primaire de production. La solution numérique de Synergates améliore la sécurité physique et opérationnelle.",
        'supermarkets': "Les supermarchés font face aux espaces morts et à la prévention des pertes. Notre solution offre une vidéosurveillance fiable et des analytics.",
        'offshore-oil-platform': "Les plateformes offshore opèrent dans des conditions difficiles. Notre solution couvre le périmètre, les équipements critiques et la salle de contrôle.",
        'transmission-line-inspection': "L'électricité doit voyager sur de longues distances. Les lignes de transmission nécessitent une surveillance continue.",
        'pipeline-inspection': "Les réseaux de pipelines nécessitent une surveillance continue. Notre solution fournit vidéo et analytics le long du tracé.",
        'solar-farms': "Les centrales solaires, souvent en zones montagneuses ou désertiques, présentent des défis de sécurité. La solution Synergates simplifie les opérations.",
        'hydroelectric-power-plants': "Les centrales hydroélectriques intègrent barrage, réservoir, salle des turbines et périmètre. Notre solution fournit une sécurité vidéo complète."
    };

    window.SCENARIO_SECTION_NAMES_FR = {
        'classroom-hub': ['Applications en classe', 'Apprentissage à distance', 'Apprentissage multi-salles', 'Gestion centralisée'],
        'urban-roadways': ['Intersections', 'Voies de circulation', 'Voie bus', 'Bord de route urbain', 'Chaussée à marquage jaune', 'Zone de divergence', 'Centres de commande'],
        'stores': ['Entrée', 'Parking', 'Zone d\'achat', 'Caisses', 'Inventaire', 'Salle informatique'],
        'bus-stop': ['Détection d\'anomalies', 'Comptage flux passagers arrêt bus', 'Diffusion vocale arrêt bus', 'Détection stationnement illégal', 'Centre opérationnel'],
        'car-dealerships': ['Parkings', 'Périmètre', 'Entrée principale', 'Showroom et zones maintenance', 'Bureau', 'Salle de contrôle'],
        'conference-rooms': ['Conférences petites et moyennes', 'Conférences moyennes et grandes'],
        'highways': ['Péages autoroutiers', 'Voies autoroutières', 'Bretelles', 'Accotements', 'Tunnels', 'Centres de commande autoroutiers'],
        'parking-lots': ['Gestion entrées et sorties', 'Guidage parking intérieur', 'Règles tarifaires parking', 'Exploitation et gestion'],
        'shopping-malls': ['Analytics flux clients', 'Publicité affichage commercial', 'Sécurité générale', 'Gestion parking intelligente'],
        'transit-bus-onboard': ['Zones passagers', 'Cabine de conduite bus', 'Entrée', 'Centre opérationnel'],
        'electrical-substations': ['Gestion exploitation et maintenance', 'Sécurité et sûreté', 'Gestion système centralisée'],
        'monitoring-center': ['Salle informatique', 'Salle de contrôle', 'Centre de monitoring'],
        'onshore-oilfields': ['Poste de contrôle', 'Puits et pipelines', 'Usine de traitement', 'Véhicules', 'Zones bureaux'],
        'supermarkets': ['Entrée', 'Parking', 'Zone d\'achat', 'Caisses', 'Inventaire', 'Salle informatique'],
        'offshore-oil-platform': ['Périmètre plateforme', 'Équipements critiques', 'Salle de contrôle'],
        'transmission-line-inspection': ['Inspection couloir', 'Inspection tours et lignes', 'Gestion sécurité opérations terrain', 'Gestion système centralisée'],
        'pipeline-inspection': ['Tracé pipeline', 'Stations de vannes', 'Passages', 'Centre de contrôle'],
        'solar-farms': ['Sécurité périmètre et accès véhicules', 'Sécurité personnel en permanence', 'Exploitation et maintenance efficaces', 'Gestion centralisée'],
        'hydroelectric-power-plants': ['Barrage et réservoir', 'Salle des turbines', 'Poste de transformation', 'Périmètre', 'Centre de contrôle']
    };

    window.SECTION_CHALLENGES_FR = {
        'classroom-hub': [
            "Les élèves s'attendent à des supports d'apprentissage interactifs et engageants. Les enseignants ont besoin d'outils simples pour gérer le contenu et connecter les salles.",
            "L'apprentissage à distance doit offrir une qualité vidéo et audio fiable. La gestion des participants et le partage de contenu doivent être fluides.",
            "L'enseignement multi-salles nécessite une visibilité sur plusieurs espaces simultanément. La coordination et la gestion centralisée sont essentielles.",
            "Les administrateurs ont besoin d'une vue d'ensemble de tous les équipements et salles. La maintenance et les mises à jour à distance simplifient les opérations."
        ],
        'urban-roadways': [
            "Les intersections urbaines subissent un trafic intense. Les infractions au feu rouge, excès de vitesse et comportements dangereux nécessitent une surveillance précise.",
            "Les voies de circulation exigent une détection des violations et du flux. La gestion des données fragmentées complique la supervision.",
            "Les voies bus dédiées font face aux empiétements. Une détection et sanction efficaces sont nécessaires pour garantir la priorité.",
            "Le bord de route urbain nécessite une surveillance des comportements à risque : stationnement illégal, piétons traversant incorrectement.",
            "Les zones à marquage jaune et de divergence sont des points critiques. Les violations aggravent la congestion et les risques.",
            "Une gestion centralisée unifiée est essentielle pour surveiller l'ensemble du réseau et coordonner les réponses.",
            "Les centres de commande doivent unifier la vidéo, les données de trafic et les systèmes de signalisation sur une plateforme."
        ],
        'stores': [
            "L'entrée doit équilibrer accès client et prévention du vol. Une visibilité claire et un flux traçable sont essentiels.",
            "Le parking doit gérer le flux véhicules, prévenir le vol et offrir des statistiques d'occupation.",
            "La zone d'achat nécessite une sécurité sans gêner l'expérience client. Les analytics de flux et de zones chaudes aident les opérations.",
            "Les caisses exigent une vue claire des transactions et une gestion des files. La prévention du vol à l'étalage est prioritaire.",
            "L'inventaire doit prévenir les pertes et dégâts. Les alertes précoces et la récupération de preuves sont critiques.",
            "La salle informatique et les zones back-office nécessitent un accès restreint et une surveillance."
        ],
        'bus-stop': [
            "La détection d'anomalies aux arrêts de bus améliore la sécurité. Les comportements suspects ou les incidents nécessitent des alertes rapides.",
            "Le comptage du flux passagers aide à planifier les fréquences et à optimiser le service.",
            "La diffusion vocale permet des annonces en temps réel et une dissuasion ou guidance des passagers.",
            "Le stationnement illégal aux arrêts gêne l'accès. Une détection et une sanction efficaces sont nécessaires.",
            "Un centre opérationnel unifié doit superviser tous les arrêts et gérer les incidents."
        ],
        'car-dealerships': [
            "Les parkings exposent des véhicules de valeur. Une gestion des entrées/sorties et une surveillance 24h/24 sont essentielles.",
            "Le périmètre doit prévenir les intrusions et offrir une visibilité claire jour et nuit.",
            "L'entrée principale gère visiteurs et clients. Un accès sécurisé et traçable est requis.",
            "Le showroom et les zones maintenance contiennent des véhicules et équipements. La sécurité et la surveillance sont critiques.",
            "Les bureaux nécessitent un contrôle d'accès et une protection des données.",
            "Une salle de contrôle unifie vidéo, accès et alarmes sur une plateforme."
        ],
        'conference-rooms': [
            "Les salles petites et moyennes ont besoin d'équipements flexibles et faciles à utiliser. La qualité vidéo et audio est essentielle.",
            "Les grandes salles exigent des systèmes évolutifs pour couvrir l'espace. La collaboration et le partage de contenu doivent être fluides."
        ],
        'electrical-substations': [
            "L'exploitation et la maintenance nécessitent une surveillance des équipements et des conditions. La détection précoce des anomalies réduit les pannes.",
            "La sécurité et la sûreté du site exigent une protection périmétrique, un contrôle d'accès et une surveillance 24h/24.",
            "Une gestion centralisée unifie les sous-systèmes pour une visibilité et un contrôle efficaces."
        ],
        'highways': [
            "Les péages gèrent un flux intense. La fraude et les erreurs de passage doivent être détectées avec des preuves claires.",
            "Les voies autoroutières nécessitent une détection des infractions : excès de vitesse, empiétement voie d'urgence, violations zone de divergence.",
            "Les bretelles et accotements sont des points critiques pour les incidents et les comportements à risque.",
            "Les tunnels exigent une surveillance et une détection des incidents en environnement fermé.",
            "Les centres de commande autoroutiers unifient la surveillance du réseau pour une gestion et une réponse efficaces.",
            "La congestion et les incidents nécessitent une détection rapide et une coordination des réponses."
        ],
        'monitoring-center': [
            "La salle informatique héberge les serveurs et l'infrastructure. La surveillance de la température et l'accès restreint sont essentiels.",
            "La salle de contrôle doit afficher et gérer les flux vidéo de multiples sources. L'ergonomie et la réactivité sont critiques.",
            "Le centre de monitoring unifie les sous-systèmes. La santé du système et la maintenance doivent être visibles."
        ],
        'parking-lots': [
            "La gestion des entrées et sorties doit être fluide aux heures de pointe. Les enregistrements véhicules doivent être consultables.",
            "Le guidage parking intérieur aide les conducteurs à trouver rapidement une place. Les statistiques d'occupation optimisent l'utilisation.",
            "Les règles tarifaires doivent être flexibles selon la durée, l'heure et le type de véhicule.",
            "L'exploitation et la gestion nécessitent une vue d'ensemble, des rapports et une maintenance des équipements."
        ],
        'shopping-malls': [
            "Les analytics de flux clients aident à optimiser la disposition des commerces et à mesurer la performance.",
            "L'affichage commercial peut générer des revenus tout en améliorant l'expérience.",
            "La sécurité générale doit couvrir les espaces communs, les parkings et les entrées.",
            "La gestion parking intelligente améliore l'expérience client et l'utilisation de l'espace."
        ],
        'transit-bus-onboard': [
            "Les zones passagers nécessitent une surveillance pour la sécurité et la prévention des incidents. Les enregistrements servent de preuves.",
            "La cabine de conduite doit être protégée. Les alertes et l'assistance à la conduite améliorent la sécurité.",
            "L'entrée du bus est un point critique pour le flux et la détection des anomalies.",
            "Un centre opérationnel centralise la gestion de la flotte et des incidents."
        ],
        'onshore-oilfields': [
            "Les postes de contrôle gèrent l'accès des véhicules et du personnel. La traçabilité et la sécurité sont essentielles.",
            "Les puits et pipelines sont dispersés et vulnérables. La surveillance à distance et la détection d'anomalies sont critiques.",
            "L'usine de traitement contient des équipements critiques. La sécurité et la surveillance des processus sont prioritaires.",
            "La gestion des véhicules sur site nécessite une identification et un suivi clairs.",
            "Les zones bureaux et logistiques requièrent un contrôle d'accès et une surveillance."
        ],
        'supermarkets': [
            "L'entrée doit équilibrer accès client et prévention du vol. Visibilité et flux traçable.",
            "Le parking gère le flux et la sécurité. Des statistiques d'occupation aident les opérations.",
            "La zone d'achat nécessite une sécurité discrète et des analytics pour optimiser la disposition.",
            "Les caisses exigent une vue des transactions et une gestion des files. Prévention du vol à l'étalage.",
            "L'inventaire prévient les pertes. Alertes et récupération de preuves.",
            "La salle informatique et back-office nécessitent un accès restreint."
        ],
        'offshore-oil-platform': [
            "Les plateformes opèrent dans des conditions éloignées et difficiles. Le périmètre doit dissuader et détecter les intrusions, navires non autorisés et menaces.",
            "Les équipements critiques doivent être protégés contre la manipulation et les défaillances. La détection précoce et des preuves claires sont essentielles.",
            "La salle de contrôle doit unifier vidéo, accès, processus et systèmes de sécurité. La visibilité limitée et la maintenance difficile augmentent les risques."
        ],
        'transmission-line-inspection': [
            "La maintenance des lignes de transmission dans des environnements dangereux pose des défis. Les inspections peu fréquentes retardent la maintenance.",
            "Les inspections terrain peuvent être dangereuses. Une inspection à distance et thermique est importante.",
            "Le manque de registres sur site et la difficulté à assurer des opérations standardisées exigent un enregistrement en temps réel.",
            "Les systèmes de gestion fragmentés empêchent l'efficacité. Une plateforme unifiée avec tableaux de bord et rapports est nécessaire."
        ],
        'pipeline-inspection': [
            "Les tracés de pipeline couvrent de longues distances et sont vulnérables aux dommages, fuites et intrusions. La surveillance complète est difficile.",
            "Les stations de vannes et de pompage sont des points critiques. L'accès non autorisé et les défaillances doivent être détectés rapidement.",
            "Les passages routiers et fluviaux sont des zones à risque. Les dommages peuvent causer des fuites ; la surveillance doit être fiable.",
            "Une salle de contrôle centrale doit superviser l'ensemble. Les données du tracé, des vannes et des passages doivent être unifiées."
        ],
        'solar-farms': [
            "En centrales solaires avec supervision limitée, la protection périmètre et la gestion véhicules doivent être simplifiées. Le thermique et l'IA sécurisent le périmètre.",
            "La solution renforce la santé et la sécurité du personnel avec une surveillance continue des zones critiques et analytics IA.",
            "La surveillance à distance avec détection précoce des problèmes d'équipement rationalise l'inspection et réduit les arrêts.",
            "La plateforme centralisée et le mur vidéo offrent une gestion centralisée avec visualisation des données et analyse."
        ],
        'hydroelectric-power-plants': [
            "Le barrage et le réservoir sont critiques pour la sécurité et les opérations. Le niveau d'eau, les infiltrations et les intrusions doivent être surveillés 24h/24.",
            "La salle des turbines contient des machines critiques et des zones à risque. La sécurité, le vol et l'état des équipements exigent une vidéo et un contrôle d'accès continus.",
            "Le poste de transformation gère les équipements haute tension. L'accès non autorisé et les défauts nécessitent une détection précoce.",
            "Le périmètre de la centrale doit protéger contre les intrusions. Les sites vastes et souvent éloignés nécessitent une couverture efficace.",
            "La salle de contrôle doit superviser barrage, turbines, poste et périmètre. Les systèmes fragmentés rendent les opérations inefficaces."
        ]
    };

    window.SECTION_WHAT_WE_OFFER_FR = {
        'electrical-substations': [
            { whatWeOfferIntro: "Synergates utilise des technologies de pointe pour surveiller les opérations électriques dans les postes. Les solutions avancées fournissent une couche de sécurité fiable et aident les gestionnaires à prédire les défaillances via des analyses vidéo intelligentes.", whatWeOfferBlocks: [
                { title: "Surveillance des actifs critiques", description: "Imagerie vidéo des actifs critiques avec mises à jour de statut en temps réel. Intégration SCADA pour une meilleure conscience de la situation. Visibilité AR sur les installations électriques ; caméras positionnelles, PTZ et réseau ; imagerie panoramique des transformateurs, disjoncteurs et tableaux.", bullets: ["Visibilité AR sur les installations électriques", "Caméras positionnelles, PTZ et réseau", "Imagerie panoramique des transformateurs et tableaux", "Intégration SCADA pour conscience de situation"], imageUrl: "images/solution-detail/s0-o0.jpg" },
                { title: "Thermographie infrarouge", description: "Détecter les anomalies de température et les incendies dès les premiers stades avec notifications rapides. Règles configurables et rapports d'événements ; cartes de distribution thermique ; mesure de température à distance.", bullets: ["Détection des anomalies et incendies en phase précoce", "Règles configurables et rapports", "Cartes de distribution thermique", "Mesure à distance"], imageUrl: "images/solution-detail/s0-o1.jpg" },
                { title: "Analytics IA et inspections intelligentes", description: "Détection du statut des actifs électriques via IA. Lecture automatisée des compteurs et voyants ; visibilité des disjoncteurs et écrans numériques ; rapports et planning en ligne avec vérification à distance.", bullets: ["Lecture automatisée des compteurs", "Visibilité des disjoncteurs et écrans", "Rapports et plateformes Synergates Central", "Planning en ligne et vérification à distance"], imageUrl: "images/solution-detail/s0-o2.jpg" }
            ]},
            { whatWeOfferIntro: "Synergates propose des caméras intelligentes, radars et outils avancés pour la sécurité des postes. Protection du personnel, détections en temps réel et alertes rapides pour une réponse incident efficace.", whatWeOfferBlocks: [
                { title: "Protection périmétrique", description: "Protection 24h/24 du périmètre et des zones critiques avec alerte immédiate en cas de violation.", bullets: ["Protection 24h/24 périmètre et zones critiques", "Alerte immédiate en cas de violation", "Détection et alertes rapides"], imageUrl: "images/solution-detail/s1-o0.jpg" },
                { title: "Contrôle entrées et sorties", description: "Barrières et terminaux de reconnaissance faciale pour un accès limité au personnel autorisé.", bullets: ["Contrôle intelligent entrées/sorties", "Accès limité au personnel autorisé", "Minimiser pertes et dangers"], imageUrl: "images/solution-detail/s1-o1.jpg" },
                { title: "Détection EPI et activités anormales", description: "Vérification à distance des casques et équipements de protection. Détection des chutes, courses et rassemblements dangereux.", bullets: ["Vérification des casques et EPI via vidéo", "Détection chutes, courses, rassemblements", "Conformité aux réglementations", "Réponse rapide des gestionnaires"], imageUrl: "images/solution-detail/s1-o2.jpg" }
            ]},
            { whatWeOfferIntro: "Synergates propose une gestion centralisée pour les postes. Avec collecte et analyse des données, les opérateurs obtiennent des insights et traitent les risques rapidement.", whatWeOfferBlocks: [
                { title: "Surveillance des processus", description: "Améliore la conscience de la situation. Suivi du processus opérationnel ; intégration SCADA avec étiquettes lisibles ; imagerie vidéo temps réel.", bullets: ["Suivi du processus opérationnel", "Intégration SCADA avec étiquettes", "Imagerie vidéo temps réel", "Amélioration conscience de situation"], imageUrl: "images/solution-detail/s2-o0.jpg" },
                { title: "Gestion des alarmes", description: "Réponse rapide aux risques. Dispatch d'urgence ; notifications d'alarme temps réel et vérification vidéo.", bullets: ["Dispatch d'urgence", "Notifications alarme temps réel", "Vérification vidéo", "Action rapide pour éviter les risques"], imageUrl: "images/solution-detail/s2-o1.jpg" },
                { title: "Tableau de bord visualisé", description: "Insights clairs via données visualisées. Vue d'ensemble et analytics multidimensionnels ; statut opérationnel temps réel.", bullets: ["Vue d'ensemble et analytics multidimensionnels", "Tableau de bord complet", "Statut opérationnel temps réel", "Insights via données visualisées"], imageUrl: "images/solution-detail/s2-o2.jpg" }
            ]}
        ],
        'monitoring-center': [
            { whatWeOfferIntro: "Stockage et affichage puissants avec tous les sous-systèmes unifiés sur une plateforme pour surveillance, gestion d'incidents, contrôle à distance et maintenance. Synergates simplifie la gestion de la salle informatique.", whatWeOfferBlocks: [
                { title: "Affichage et disposition flexibles", description: "Planification d'affichage et modèles de disposition pour un affichage efficace. Options professionnelles ; fonctionnement fiable avec haute clarté.", bullets: ["Planification et modèles flexibles", "Affichage efficace à coûts réduits", "Options professionnelles", "Fonctionnement fiable haute clarté"], imageUrl: "images/solution-detail/s0-o0.jpg" },
                { title: "Écrans compatibles VESA", description: "Jusqu'à 4 écrans par serveur Synergates Central. Moniteurs bureau ou mur de 1080p à 4K.", bullets: ["Jusqu'à 4 écrans par serveur", "Bureau ou mur 1080p à 4K", "Écrans compatibles VESA"], imageUrl: "images/solution-detail/s0-o1.jpg" }
            ]},
            { whatWeOfferIntro: "Affichage mural vidéo professionnel avec tous les sous-systèmes unifiés pour une gestion de salle de contrôle plus simple et efficace.", whatWeOfferBlocks: [
                { title: "Mur vidéo et décodage", description: "Planification et disposition flexibles ; décodage puissant ; choix professionnels variés. Fonctionnement fiable ; nombreuses caméras simultanées. Support murs vidéo LCD jusqu'à 4x4.", bullets: ["Planification et disposition flexibles", "Décodage puissant", "Support murs vidéo LCD 4x4", "Nombreuses caméras simultanées"], imageUrl: "images/solution-detail/s1-o0.jpg" }
            ]},
            { whatWeOfferIntro: "Stockage et affichage puissants avec tous les sous-systèmes unifiés pour une gestion du centre de monitoring plus simple et efficace.", whatWeOfferBlocks: [
                { title: "Gestion de contenu professionnelle", description: "Choix professionnels variés. Affichages caméra multiples ; formats de signal et sortie variés ; mur vidéo LCD/LED et décodage. Gestion planification et disposition ; fiabilité 24h/24.", bullets: ["Gestion planification et disposition", "Fiabilité 24h/24 haute clarté", "Support nombreux écrans LCD/LED", "Affichages caméra multiples"], imageUrl: "images/solution-detail/s2-o0.jpg" }
            ]}
        ],
        'classroom-hub': [
            { whatWeOfferIntro: "Notre Classroom Hub étend les salles réelles aux salles numériques et virtuelles. Outils d'enseignement intelligents et logiciels faciles aident les enseignants à livrer des cours plus engageants. Au-delà de la craie et du tableau, création de contenu interactif et partage entre appareils et salles.", whatWeOfferBlocks: [
                { title: "Écran plat interactif", description: "Outil d'enseignement numérique intégrant tactile, affichage HD et ressources tierces. Création d'instruction numérique et collaboration multi-utilisateurs. Projection sans fil et partage de contenu.", bullets: ["Tactile multi-points IR jusqu'à 20", "Projection sans fil smartphone, tablette, PC", "Filtre lumière bleue pour les yeux", "Ressources et applications tierces"], imageUrl: "images/solution-detail/s0-o0.jpg" },
                { title: "Logiciel tableau blanc flexible", description: "Création et partage d'instruction numérique avec expériences visuelles. Ouverture aux applications tierces et projection multi-terminaux.", bullets: ["Possibilités avec applications tierces", "Expériences visuelles au-delà du tableau", "Projection multi-terminaux pour travaux en groupe", "Création et publication flexibles"], imageUrl: "images/solution-detail/s0-o1.jpg" }
            ]},
            { whatWeOfferIntro: "L'apprentissage à distance partage l'instruction avec les élèves hors salle. Caméras IA et logiciels professionnels pour engagement élevé et configuration simple, compatibles avec les outils de visioconférence courants.", whatWeOfferBlocks: [
                { title: "Caméra enseignant et ClassIn", description: "Partage en temps réel des scénarios d'enseignement et supports avec les élèves à distance.", bullets: ["Suivi caméra et plan rapproché", "Images HD enseignant et tableau", "Compatible Zoom, Webex et plus"], imageUrl: "images/solution-detail/s1-o0.jpg" },
                { title: "Basculement fluide", description: "Bascule enseignant/tableau en excellente qualité pour un environnement immersif.", bullets: ["Qualité jusqu'à 1080p", "Configuration simple", "Haute compatibilité"], imageUrl: "images/solution-detail/s1-o1.jpg" }
            ]},
            { whatWeOfferIntro: "L'apprentissage multi-salles permet un enseignement synchronisé entre plusieurs salles pour un accès élargi au meilleur contenu éducatif.", whatWeOfferBlocks: [
                { title: "Enseignement synchronisé", description: "Supports, audio et annotations sur l'écran interactif synchronisés aux autres salles en temps réel.", bullets: ["Salle principale avec trois secondaires", "ClassLink pour vues d'enseignement flexibles", "Même niveau de ressources pour zones éloignées"], imageUrl: "images/solution-detail/s2-o0.jpg" },
                { title: "Retour élèves", description: "Les enseignants voient les retours de tous les élèves pour garantir la qualité.", bullets: ["Meilleur engagement", "Évaluer la réaction aux cours", "Améliorer la qualité d'enseignement"], imageUrl: "images/solution-detail/s2-o1.jpg" }
            ]},
            { whatWeOfferIntro: "FocSign permet une configuration par lot et une gestion centralisée des écrans interactifs dans les établissements.", whatWeOfferBlocks: [
                { title: "Configuration par lot", description: "Gestion à distance de plusieurs panneaux : paramètres, affichage d'information, installation rapide d'applications.", bullets: ["Installation en un clic multi-appareils", "Messages courts multi-appareils", "Arrêt, redémarrage, restauration à distance"], imageUrl: "images/solution-detail/s3-o0.jpg" },
                { title: "Efficacité administrative", description: "Augmenter l'efficacité administrative et optimiser le temps en classe avec un contrôle centralisé.", bullets: ["Deux modes d'affichage d'information", "Livraison rapide des mises à jour", "Économie d'énergie et sécurité"], imageUrl: "images/solution-detail/s3-o1.jpg" }
            ]}
        ],
        'parking-lots': [
            { whatWeOfferIntro: "Entrée et sortie fluides avec plaques autorisées et enregistrements véhicules faciles à consulter. Réduction de la congestion aux heures de pointe, collecte simplifiée des preuves en cas de litige, visibilité sur le flux et l'occupation. Plateforme unique pour règles tarifaires flexibles, appel centre distant et rapports détaillés.", whatWeOfferBlocks: [
                { title: "Gestion entrées et sorties", description: "Produits ANPR avec alarme liste noire, comptage véhicules et passage sans arrêt. Véhicules autorisés fluidifiés, véhicules non autorisés identifiés.", bullets: ["Soulagement congestion heures de pointe", "Collecte preuves simplifiée pour litiges", "Enregistrements et recherche floue plaque", "Appel centre distant quand guichet fermé"], imageUrl: "images/solution-detail/s0-o0.jpg" },
                { title: "Enregistrements véhicules", description: "Enregistrement plaques, images et vidéo avec recherche floue et filtre d'événements. Correction manuelle et gestion liste noire.", bullets: ["Appel centre distant guichet fermé", "Correction manuelle et contrôle barrière", "Alarme liste noire et surveillance véhicules", "Statistiques et rapports"], imageUrl: "images/solution-detail/s0-o1.jpg" }
            ]},
            { whatWeOfferIntro: "Le guidage parking intérieur aide les conducteurs à trouver rapidement les places libres et à localiser leur véhicule. Caméras de guidage pour données d'occupation temps réel ; panneaux toujours à jour. Réduit le temps de recherche et le stress aux heures de pointe.", whatWeOfferBlocks: [
                { title: "Système de guidage parking", description: "Affichage des places libres par direction avec données des caméras de guidage. Efficacité heures de pointe et vue claire des places disponibles.", bullets: ["Efficacité heures de pointe, moins de recherche", "Consultation libre-service emplacement véhicule", "Indications lumineuses multicolores", "Occupation temps réel par zone et niveau"], imageUrl: "images/solution-detail/s1-o0.jpg" },
                { title: "Guidage visuel", description: "Guidage visuel complet pour trouver rapidement les places et localiser le véhicule garé.", bullets: ["Affichage nombre et emplacement des places", "Direction vers places libres", "Moins de stress dans les grands parkings", "Consultation emplacement véhicule libre-service"], imageUrl: "images/solution-detail/s1-o1.jpg" }
            ]},
            { whatWeOfferIntro: "Règles tarifaires flexibles et enregistrements de paiement consultables. Réductions, coupons, cartes et tickets configurables. Données pour rapports et litiges. Gestion basée sur les données et anti-fraude.", whatWeOfferBlocks: [
                { title: "Configuration règles tarifaires", description: "Support réductions, coupons, cartes et tickets. Paiement à la sortie, prépaiement au péage ou rechargement compte. Liaison plaque et reçu automatique.", bullets: ["Paiement à la sortie, prépaiement ou rechargement", "Liaison plaque et affichage reçu", "Règles réductions, coupons, adhésion", "Modèles de configuration courants"], imageUrl: "images/solution-detail/s2-o0.jpg" },
                { title: "Prévention des pertes", description: "Gestion basée sur les données et tactiques anti-fraude. Rapports et tableaux de bord pour anomalies et pertes.", bullets: ["Gestion et rapports basés sur les données", "Prévention des pertes et protection des revenus", "Configuration courante et dérogations", "Piste d'audit des transactions"], imageUrl: "images/solution-detail/s2-o1.jpg" }
            ]},
            { whatWeOfferIntro: "Statistiques de gestion et enregistrements détaillés pour entrées/sorties, flux véhicules et utilisation des places. Résolution rapide des litiges avec preuves claires.", whatWeOfferBlocks: [
                { title: "Rapports opérationnels et transactions", description: "Enregistrements détaillés entrées/sorties, statistiques flux et utilisation des places. Vidéo et plaques pour preuves fiables.", bullets: ["Enregistrement vidéo pour litiges", "Consultation enregistrements par reconnaissance plaque", "Règles d'accès personnalisables et rapports"], imageUrl: "images/solution-detail/s3-o0.jpg" },
                { title: "Gestion visuelle", description: "Rapports et tableaux de bord variés pour insights opérationnels et optimisation.", bullets: ["Facturation et gestion visuelle", "Insights opérationnels", "Exploitation parking et suivi revenus"], imageUrl: "images/solution-detail/s3-o1.jpg" }
            ]}
        ],
        'urban-roadways': [
            { whatWeOfferIntro: "Notre solution Urban Roadways offre une surveillance multi-scènes et une supervision des conduites illégales pour réduire les infractions et protéger les citoyens. Logiciel intelligent et preuves HD pour une application cohérente. Vidéo temps réel aux intersections capture les violations.", whatWeOfferBlocks: [
                { title: "Détection des infractions aux intersections", description: "Vidéo temps réel aux intersections capture les violations et collecte des preuves HD. Les caméras servent d'avertissement visible aux conducteurs.", bullets: ["Application standardisée et moins de litiges", "Détection feu rouge, sens interdit, etc.", "Données véhicule : LPR, couleur, marque, type"], imageUrl: "images/solution-detail/s0-o0.jpg" },
                { title: "Déploiement tout-en-un flexible", description: "Unités de capture ou caméras trafic adaptées aux sites et budgets. Détecteurs de signal et stroboscopes pour couverture complète.", bullets: ["Design tout-en-un pour coûts réduits", "Plusieurs types d'infractions depuis un système", "Preuves et alertes pour réponse rapide"], imageUrl: "images/solution-detail/s0-o1.jpg" }
            ]},
            { whatWeOfferIntro: "Surveillance de la vitesse et détection des données de trafic pour gérer les voies plus sûrement. Calcul vitesse temps réel et analyse du flux pour application et guidage intelligent.", whatWeOfferBlocks: [
                { title: "Système de surveillance de vitesse", description: "Calcul des vitesses en temps réel et collecte de preuves pour dissuasion et application de la loi.", bullets: ["Application standardisée, moins de litiges manuels", "Avertissement préalable tunnels et sections critiques", "Données véhicule et preuves forensiques"], imageUrl: "images/solution-detail/s1-o0.jpg" },
                { title: "Détection des informations trafic", description: "Données trafic temps réel pour meilleures décisions. Détection état route : fluide, lente, congestionnée ; prévision du flux.", bullets: ["Conditions trafic temps réel pour meilleur guidage", "Prévision flux et détection congestion", "Données flux, vitesse, file, occupation"], imageUrl: "images/solution-detail/s1-o1.jpg" }
            ]},
            { whatWeOfferIntro: "Surveillance des voies bus capture les violations et collecte des preuves. Téléchargement automatique et détection des caractéristiques véhicules pour application à distance efficace.", whatWeOfferBlocks: [
                { title: "Surveillance voie bus", description: "Vidéo 24h/24 capture les violations et collecte les preuves. Détection caractéristiques véhicules et stationnement illégal.", bullets: ["Application standardisée, moins de charge personnel", "Téléchargement automatique véhicules en infraction", "Couverture large avec images nettes"], imageUrl: "images/solution-detail/s2-o0.jpg" },
                { title: "Détection stationnement illégal", description: "Détection précise des véhicules en stationnement illégal avec images nettes. Détection multi-scènes.", bullets: ["Téléchargement automatique pour gestion preuves", "Données véhicule : LPR, couleur, type", "Voies bus et bords de route dégagés"], imageUrl: "images/solution-detail/s2-o1.jpg" }
            ]},
            { whatWeOfferIntro: "L'espace en bord de route urbain est limité ; stationnement prolongé et manque d'application créent la congestion. Vidéo capture les violations et collecte des preuves HD pour gestion à distance et contraventions.", whatWeOfferBlocks: [
                { title: "Gestion du stationnement bord de route", description: "Vidéo 24h/24 capture les violations de stationnement et collecte des preuves HD. Détection précise des véhicules garés.", bullets: ["Réduire le stationnement illégal en bord de route", "Détection et gestion à distance par vidéo", "Données structurées pour recherche et preuves"], imageUrl: "images/solution-detail/s3-o0.jpg" },
                { title: "Efficacité de l'application", description: "Application standardisée et prévention de la congestion. Garder les véhicules en mouvement et l'espace libre.", bullets: ["Prévenir congestion et garder le flux fluide", "Preuves pour contraventions et litiges", "Réduire les stationnements prolongés"], imageUrl: "images/solution-detail/s3-o1.jpg" }
            ]},
            { whatWeOfferIntro: "Les chaussées à marquage jaune aux intersections et près des écoles ou hôpitaux doivent rester dégagées. Vidéo capture les violations et collecte les preuves, avertissement visible et application cohérente.", whatWeOfferBlocks: [
                { title: "Détection violations chaussée jaune", description: "Vidéo aux chaussées jaunes capture les violations et collecte les preuves. Avertissement visible et application cohérente.", bullets: ["Améliorer sécurité et ordre aux intersections", "Réduire infractions et accidents", "Données véhicule pour preuves et recherche"], imageUrl: "images/solution-detail/s4-o0.jpg" },
                { title: "Congestion et conformité", description: "Détection des véhicules entrant en zone jaune en cas de congestion. Réguler le trafic et garantir la sécurité.", bullets: ["Application standardisée", "Prévenir conflits police-citoyens", "Preuves claires pour litiges"], imageUrl: "images/solution-detail/s4-o1.jpg" }
            ]},
            { whatWeOfferIntro: "Les zones de divergence guident les conducteurs ; les traverser augmente accidents et congestion. Vidéo 24h/24 capture les violations et enregistre le processus aux bretelles.", whatWeOfferBlocks: [
                { title: "Détection traversée zone divergence", description: "Vidéo 24h/24 aux zones de divergence capture les violations et enregistre le processus complet. Réguler la conduite aux bretelles.", bullets: ["Processus d'application standardisés", "Réduire litiges d'intervention manuelle", "Processus de violation enregistré pour preuves"], imageUrl: "images/solution-detail/s5-o0.jpg" },
                { title: "Sécurité bretelles et approche", description: "Données véhicule pour LPR, couleur, type, marque. Réduire les violations aux bretelles et améliorer la sécurité.", bullets: ["Réguler conduite aux bretelles et réduire accidents", "Preuves rapides pour résolution incidents", "Surveillance bretelles entrée et sortie"], imageUrl: "images/solution-detail/s5-o1.jpg" }
            ]},
            { whatWeOfferIntro: "Les centres de commande doivent gérer de nombreux appareils et processus. Notre logiciel et matériel forment un système full-stack, plateforme modulaire pour tous les scénarios de voies urbaines.", whatWeOfferBlocks: [
                { title: "Plateforme centre de commande", description: "Comprendre l'état des routes urbaines en temps réel pour décisions intelligentes. Centraliser les données complexes avec tableaux de bord et gestion des alarmes.", bullets: ["Système centralisé pour tous les appareils", "Recherche attributs véhicule et centre d'alarmes", "Analyses statistiques et tableaux de bord"], imageUrl: "images/solution-detail/s6-o0.jpg" },
                { title: "Gestion violations et incidents", description: "Gérer les violations avec efficacité améliorée. Localiser rapidement les véhicules par plaque ou attributs.", bullets: ["Gestion violations et efficacité application", "Localisation rapide par plaque ou attributs", "Vue unifiée du statut route et événements"], imageUrl: "images/solution-detail/s6-o1.jpg" }
            ]}
        ],
        'stores': [
            { whatWeOfferIntro: "Nous combinons une vidéosurveillance fiable avec des analytics intelligents pour la gestion quotidienne des magasins. De l'entrée à la caisse, comprendre le flux clients, prévenir les pertes et améliorer le service, avec preuves claires. Données précises de visites et analyse du trafic à l'entrée.", whatWeOfferBlocks: [
                { title: "Analytics flux clients", description: "Données précises de visites et analyse du trafic à l'entrée pour optimiser opérations et marketing. Évaluer l'efficacité des campagnes et surveiller les risques avec l'IA.", bullets: ["Statistiques multi-caméras et export rapports", "Évaluer événements marketing et taux d'entrée", "Rapports configurables", "Insights flux heures de pointe et par zone"], imageUrl: "images/solution-detail/s0-o0.jpg" },
                { title: "Prévention des pertes renforcée", description: "Identifier les individus suspects et alertes précoces pour voleurs connus. Alarme temps réel via application mobile et notification VIP ou risque.", bullets: ["Identifier les personnes suspectes via reconnaissance IA", "Alarme voleurs et alertes précoces", "Alarme temps réel et vérification vidéo", "Notification VIP et risque sur appareils"], imageUrl: "images/solution-detail/s0-o1.jpg" }
            ]},
            { whatWeOfferIntro: "Parking et guidage intérieur créent une forte première impression et réduisent la congestion. Entrée et sortie sans arrêt, paiement flexible et localisation facile du véhicule.", whatWeOfferBlocks: [
                { title: "Gestion entrées et sorties", description: "Entrée et sortie fluides avec ANPR et options de paiement flexibles. Collecte de preuves simplifiée et enregistrements véhicules détaillés.", bullets: ["Reconnaissance et enregistrement plaques", "Paiement frais parking en ligne ou hors ligne", "Paiement rapide et efficacité trafic"], imageUrl: "images/solution-detail/s1-o0.jpg" },
                { title: "Guidage parking intérieur", description: "Aider les clients à trouver les places et localiser leur véhicule. Cartes visualisées et indications multicolores.", bullets: ["Carte sur borne de consultation véhicule", "Indications lumineuses multicolores statut places", "Places libres sur écrans de guidage"], imageUrl: "images/solution-detail/s1-o1.jpg" }
            ]},
            { whatWeOfferIntro: "Sécurité et analytics de la zone d'achat protègent personnel, clients et actifs tout en soutenant les décisions de disposition et marchandisage. Vidéo HD grand angle et analyse carte thermique.", whatWeOfferBlocks: [
                { title: "Sécurité vidéo", description: "Pas d'angles morts avec couverture HD grand angle. Gestion d'urgence et interphonie vidéo bidirectionnelle.", bullets: ["Vidéo haute qualité 24h/24", "Surveillance bidirectionnelle et options PTZ", "Options panoramique 360° et fisheye"], imageUrl: "images/solution-detail/s2-o0.jpg" },
                { title: "Carte thermique et analytics", description: "Comprendre la distribution des clients et le temps de séjour. Rapports graphiques pour ajuster disposition, rayonnages et qualité de service.", bullets: ["Rapports graphiques fréquence et temps de séjour", "Identifier les zones à forte attention", "Disposer rayonnages et promotions par données"], imageUrl: "images/solution-detail/s2-o1.jpg" }
            ]},
            { whatWeOfferIntro: "À la caisse, la vidéosurveillance soutient la vérification des transactions, la gestion des files et la prévention des pertes. Vérification visuelle et alarmes rapides.", whatWeOfferBlocks: [
                { title: "Vérification visuelle", description: "Vérification vidéo des enregistrements caisse et recherche par mots-clés transaction avec correspondance floue.", bullets: ["Vérification vidéo des enregistrements caisse", "Recherche par mots-clés transaction, correspondance floue", "Audit visuel pour résolution rapide des litiges"], imageUrl: "images/solution-detail/s3-o0.jpg" },
                { title: "File et prévention des pertes", description: "Optimiser l'expérience de file avec alarme sur dépassement ou personnel insuffisant. Intégration EAS ou alarme intrusion.", bullets: ["Temps d'attente réduits et meilleure expérience", "Zones de détection flexibles et vidéo basse luminosité", "Alarme temps réel sur mobile ou web"], imageUrl: "images/solution-detail/s3-o1.jpg" }
            ]},
            { whatWeOfferIntro: "L'inventaire et les zones back-office bénéficient du contrôle d'accès, de la vidéo 24h/24 et des alarmes précoces. Accès sans contact, détection température et intrusion, vérification vidéo.", whatWeOfferBlocks: [
                { title: "Accès et alarme", description: "Accès sans contact anti-usurpation avec vérification vidéo. Alarmes anomalie température et intrusion avec push instantané et vidéo HD.", bullets: ["Vérification vidéo température, intrusion, accès", "Détecteurs d'alarme sans fil, déploiement facile", "Pré-alertes incendie et menaces"], imageUrl: "images/solution-detail/s4-o0.jpg" },
                { title: "Couverture 24h/24", description: "Vidéo HD grand angle et imagerie thermique optionnelle pour stockage froid et zones sensibles.", bullets: ["Vidéo HD grand angle 24h/24", "Caméra cryogénique pour stockage froid", "Fisheye et multi-lentilles pour couverture complète"], imageUrl: "images/solution-detail/s4-o1.jpg" }
            ]},
            { whatWeOfferIntro: "Les salles informatique et de contrôle combinent plusieurs sous-systèmes. Plateforme unifiée avec interface personnalisable et tableaux de bord clairs pour gérer vidéo, accès, alarme et présence.", whatWeOfferBlocks: [
                { title: "Gestion unifiée et tableau de bord", description: "Tous les sous-systèmes sur une plateforme avec disposition personnalisable et surveillance santé. Écrans haute clarté et murs vidéo.", bullets: ["Gestion centralisée vidéo, accès, alarme, présence", "Tableaux de bord santé système et appareils", "Interface personnalisable et vue d'ensemble"], imageUrl: "images/solution-detail/s5-o0.jpg" },
                { title: "Audit à distance", description: "Audit image et vidéo pour besoins variés. Vérifier à distance la situation du magasin avec images capturées et zoom.", bullets: ["Audit image et vidéo pour besoins variés", "Images capturées sous plusieurs angles", "Zoom pour voir les détails à distance"], imageUrl: "images/solution-detail/s5-o1.jpg" }
            ]}
        ],
        'onshore-oilfields': [
            { whatWeOfferIntro: "Synergates répond aux défis des postes de contrôle avec des technologies de pointe. Outils pour surveiller véhicules et personnel aux postes, identifier les menaces et permettre des réponses rapides.", whatWeOfferBlocks: [
                { title: "Mesure automatique de vitesse", description: "Le système de mesure automatique surveille les véhicules pour une conduite sûre. Les excès de vitesse sont signalés au centre et affichés sur écran LED.", bullets: ["Surveiller les véhicules pour conduite sûre", "Excès de vitesse signalés au centre", "Affichage sur écran LED"], imageUrl: "images/solution-detail/s0-o0.jpg" },
                { title: "Gestion entrées et sorties", description: "Le système de barrière gère efficacement les entrées et sorties en détectant et enregistrant les informations véhicules. Seuls les véhicules autorisés.", bullets: ["Caméra ANPR et barrière", "Détecter et enregistrer les informations véhicules", "Seuls les véhicules autorisés"], imageUrl: "images/solution-detail/s0-o1.jpg" },
                { title: "Contrôle d'accès personnel", description: "Le système d'authentification utilise les biométries pour des enregistrements d'accès précis. Gestion des visiteurs en ligne pour contrôle complet du parcours.", bullets: ["Authentification biométrique", "Enregistrements d'accès précis", "Contrôle complet du parcours visiteurs"], imageUrl: "images/solution-detail/s0-o2.jpg" }
            ]},
            { whatWeOfferIntro: "Synergates fournit un système de détection d'intrusion pour protéger les infrastructures. Algorithmes de deep learning réduisent les fausses alarmes ; surveillance vidéo 24h/24 avec notifications temps réel.", whatWeOfferBlocks: [
                { title: "Fausses alarmes réduites", description: "Les algorithmes de deep learning réduisent les fausses alarmes dues aux animaux, pluie ou feuilles. Détection des personnes ou véhicules uniquement.", bullets: ["Deep learning réduit les fausses alarmes", "Détection personnes ou véhicules uniquement", "Caméras antidéflagrantes et thermiques"], imageUrl: "images/solution-detail/s1-o0.jpg" },
                { title: "Surveillance vidéo 24h/24", description: "Surveillance vidéo 360° détecte les attaques et dommages aux pipelines avec notifications temps réel. Caméras solaires pour environnements extrêmes.", bullets: ["Surveillance vidéo 360°", "Notifications temps réel", "Caméras solaires pour installations à distance"], imageUrl: "images/solution-detail/s1-o1.jpg" }
            ]},
            { whatWeOfferIntro: "Synergates utilise des produits et plateformes leaders pour maximiser productivité et efficacité du personnel. Caméras antidéflagrantes, thermographie et détection de fuites de gaz, vérification EPI par IA.", whatWeOfferBlocks: [
                { title: "Surveillance des processus", description: "Caméras antidéflagrantes pour détection de sécurité complète. Intégration SCADA pour vérifications vidéo à distance.", bullets: ["Vues panoramiques et détaillées", "Intégration SCADA", "Surveillance temps réel 24h/24"], imageUrl: "images/solution-detail/s2-o0.jpg" },
                { title: "Conformité sécurité personnel et inspections intelligentes", description: "Les dispositifs IA vérifient la présence des EPI. Technologies IA, imagerie vidéo et logiciels pour inspections traçables et régulées.", bullets: ["Vérification EPI via IA", "Processus d'inspection traçable", "Planning en ligne et réponse temps réel"], imageUrl: "images/solution-detail/s2-o1.jpg" }
            ]},
            { whatWeOfferIntro: "Synergates propose des systèmes de surveillance mobile pour protéger les personnes et prévenir les accidents à la conduite. Surveillance véhicule temps réel améliore le GPS avec vidéo ; surveillance du conducteur par analytics IA.", whatWeOfferBlocks: [
                { title: "Surveillance véhicule temps réel", description: "Améliore le GPS avec surveillance vidéo pour préserver les preuves. Boutons d'alarme en véhicule pour sécurité.", bullets: ["Surveillance vidéo avec GPS", "Preuves pour examen des incidents", "Boutons d'alarme en véhicule"], imageUrl: "images/solution-detail/s3-o0.jpg" },
                { title: "Surveillance du statut conducteur", description: "Produits analytics IA pour prévenir fatigue au volant ou utilisation du téléphone.", bullets: ["Analytics IA pour statut conducteur", "Prévenir la fatigue au volant", "Détection utilisation téléphone"], imageUrl: "images/solution-detail/s3-o1.jpg" }
            ]},
            { whatWeOfferIntro: "Avec les outils et technologies Synergates, créer un environnement de travail organisé, sûr et productif. Rassemblement d'urgence ; mur vidéo et tableau de bord pour compréhension intuitive du statut.", whatWeOfferBlocks: [
                { title: "Rassemblement d'urgence", description: "En cas d'incendie, le capteur déclenche automatiquement l'ouverture des échappatoires. Broadcasts, SMS et autres mesures pour rassembler le personnel en lieu sûr.", bullets: ["Déclenchement auto des échappatoires", "Broadcasts et rappels SMS", "Rassembler le personnel en lieu sûr"], imageUrl: "images/solution-detail/s4-o0.jpg" },
                { title: "Gestion centralisée", description: "Le mur vidéo facilite la visualisation des flux en plusieurs points. Tableau de bord de données pour compréhension intuitive et efficacité managériale.", bullets: ["Mur vidéo en plusieurs points", "Tableau de bord de données", "Améliorer l'efficacité managériale"], imageUrl: "images/solution-detail/s4-o1.jpg" }
            ]}
        ],
        'transmission-line-inspection': [
            { whatWeOfferIntro: "Synergates propose un système vidéo fiable pour la surveillance 24h/24 des opérations électriques. Détection et alarmes temps réel pour réponse rapide. Solution radar et solution vidéo solaire pour environnements difficiles.", whatWeOfferBlocks: [
                { title: "Solution radar", description: "Le radar intégré aux caméras détecte les intrusions par personnel, véhicules et machines. Prévenir les dommages ; réduire les fausses alarmes ; envoyer les alarmes au centre.", bullets: ["Détecter intrusions personnel, véhicules, machines", "Réduire fausses alarmes causées par les arbres", "Envoyer alarmes au centre de commande"], imageUrl: "images/solution-detail/s0-o0.jpg" },
                { title: "Solution vidéo solaire", description: "Caméras solaires pour pipelines à longue portée. Surveillance continue haute résolution ; sans contrainte d'alimentation ; détection intrusions, problèmes équipement, fumée ou feu.", bullets: ["Surveillance continue haute résolution", "Sans contrainte d'alimentation", "Détecter intrusions, problèmes équipement, fumée ou feu"], imageUrl: "images/solution-detail/s0-o1.jpg" }
            ]},
            { whatWeOfferIntro: "Le système de sécurité vidéo effectue des inspections de routine en capturant automatiquement des images HD des composants. Les gestionnaires restent informés des situations sur site même à distance.", whatWeOfferBlocks: [
                { title: "Inspection d'images à distance", description: "La plateforme capture des images des composants de tour selon une liste prédéfinie, permettant une évaluation en ligne rapide.", bullets: ["Images selon liste prédéfinie", "Évaluer le statut équipement en ligne", "Inspection rapide depuis bureau distant"], imageUrl: "images/solution-detail/s1-o0.jpg" },
                { title: "Inspection thermique température", description: "Les caméras thermiques détectent les changements de température. Vérification automatique des points spécifiés et images optiques pour évaluer l'état des équipements.", bullets: ["Détecter changements de température", "Vérifier les points spécifiés automatiquement", "Évaluer l'état des équipements électriques"], imageUrl: "images/solution-detail/s1-o1.jpg" }
            ]},
            { whatWeOfferIntro: "Les produits numériques Synergates améliorent les opérations terrain pour les standardiser et sécuriser. Enregistrement temps réel des processus et supervision rationalisée pour procédures de sécurité et formation.", whatWeOfferBlocks: [
                { title: "Enregistrement temps réel des processus", description: "Caméras portables enregistrent du point de vue du travailleur ou tiers. Le centre peut vérifier les procédures et assister par intercom bidirectionnel.", bullets: ["Enregistrement point de vue travailleur ou tiers", "Vérifier les procédures de sécurité", "Assistance intercom bidirectionnel"], imageUrl: "images/solution-detail/s2-o0.jpg" },
                { title: "Supervision rationalisée des opérations", description: "La plateforme Synergates Central alloue efficacement les appareils et gère la planification. Sauvegarde des documents et preuves vidéo pour formation.", bullets: ["Allocation efficace et planification", "Sauvegarde documents et preuves vidéo", "Utilisation pour formation"], imageUrl: "images/solution-detail/s2-o1.jpg" }
            ]},
            { whatWeOfferIntro: "Synergates fournit une plateforme pour la visualisation et l'analyse des données, améliorant la gestion des incidents et l'efficacité de maintenance. Tableau de bord et rapports multidimensionnels.", whatWeOfferBlocks: [
                { title: "Tableau de bord visualisé", description: "Insights clairs via données visualisées. Répondre rapidement aux urgences et alarmes ; tableau de bord complet ; statut opérationnel temps réel.", bullets: ["Répondre aux urgences et alarmes", "Tableau de bord complet avec données intuitives", "Statut opérationnel temps réel"], imageUrl: "images/solution-detail/s3-o0.jpg" },
                { title: "Rapports multidimensionnels", description: "Rapports variés pour maintenance des appareils. Aider à la planification du personnel et à la programmation ; statut temps réel et données historiques.", bullets: ["Rapports pour maintenance appareils", "Planification personnel et programmation", "Statut temps réel et données historiques"], imageUrl: "images/solution-detail/s3-o1.jpg" }
            ]}
        ],
        'solar-farms': [
            { whatWeOfferIntro: "Dans les centrales solaires à supervision limitée, les technologies thermiques et IA de Synergates simplifient la protection périmétrique et la gestion des véhicules. Sécuriser le site et rationaliser l'accès.", whatWeOfferBlocks: [
                { title: "Protection périmétrique", description: "Produits de qualité pour détecter et protéger contre les menaces. Caméras thermiques pour surveillance 24h/24 ; radar et liaisons PTZ ; caméras solaires sans câblage supplémentaire.", bullets: ["Caméras thermiques pour surveillance 24h/24", "Radar et liaisons PTZ", "Caméras solaires sans câblage supplémentaire"], imageUrl: "images/solution-detail/s0-o0.jpg" },
                { title: "Gestion des véhicules", description: "Contrôle efficace des entrées et sorties des véhicules. Caméras IA identifient les véhicules en basse luminosité avec données d'attributs détaillées.", bullets: ["Contrôle efficace entrées et sorties", "Identification véhicules par IA en basse luminosité", "Données d'attributs pour vérification"], imageUrl: "images/solution-detail/s0-o1.jpg" }
            ]},
            { whatWeOfferIntro: "La solution centrales solaires Synergates renforce la santé et la sécurité du personnel avec surveillance continue des zones critiques via analytics IA. Identifier, gérer et prévenir les risques.", whatWeOfferBlocks: [
                { title: "Gestion du contrôle d'accès", description: "Le système d'authentification renforce la sécurité en assurant un contrôle strict et un accès autorisé dans les zones critiques. Check-in et check-out des visiteurs sur Synergates Central.", bullets: ["Contrôle strict et accès autorisé", "Check-in et check-out visiteurs sur Synergates Central", "Renforcer la sécurité du personnel"], imageUrl: "images/solution-detail/s1-o0.jpg" },
                { title: "Conformité sécurité personnel", description: "Les dispositifs IA vérifient la présence des EPI, prévenant les dangers et assurant la conformité légale. Caméras corps et casque pour enregistrement et preuves.", bullets: ["Vérifier la présence des EPI", "Prévenir les dangers", "Conformité légale sécurité"], imageUrl: "images/solution-detail/s1-o1.jpg" }
            ]},
            { whatWeOfferIntro: "Surveillance à distance avec détection précoce des problèmes d'équipement rationalise et numérise l'inspection, minimisant les arrêts et maximisant l'efficacité.", whatWeOfferBlocks: [
                { title: "Processus d'inspection standardisé", description: "Synergates simplifie l'inspection en mettant planification, exécution et rapports en ligne. Chaque étape est traçable. Statistiques et graphiques pour chaque élément.", bullets: ["Planification, exécution, rapports en ligne", "Chaque étape traçable", "Statistiques et graphiques"], imageUrl: "images/solution-detail/s2-o0.jpg" },
                { title: "Options de gamme de produits diversifiée", description: "Options pour inspections à distance et sur site : thermique et vidéo à distance ; dispositifs portables, caméras corps et casque, intercom bidirectionnel sur site.", bullets: ["Inspection à distance thermique et vidéo", "Inspection sur site avec dispositifs portables", "Caméras corps et casque"], imageUrl: "images/solution-detail/s2-o1.jpg" }
            ]},
            { whatWeOfferIntro: "La plateforme Synergates Central et le système de mur vidéo offrent une gestion centralisée pour les centrales solaires. Collecte et analyse de données visualisées pour insights opérationnels.", whatWeOfferBlocks: [
                { title: "Tableau de bord centralisé", description: "Insights clairs via données visualisées. Statut d'inspection temps réel des opérations terrain ; tableau de bord complet ; vue d'ensemble et analytics multidimensionnels.", bullets: ["Statut d'inspection temps réel", "Tableau de bord complet", "Vue d'ensemble et analytics multidimensionnels"], imageUrl: "images/solution-detail/s3-o0.jpg" }
            ]}
        ]
    };

    window.PLACEHOLDER_INTRO_FR = "Solution de sécurité et de technologie complète pour ce scénario.";
    window.PLACEHOLDER_SECTION_FR = {
        title: "Vue d'ensemble",
        challenges: "Les organisations font face à des défis opérationnels et de sécurité.",
        challengeImg1: "Défis opérationnels",
        challengeImg2: "Exigences de sécurité",
        whatWeOffer: "Nous proposons des solutions vidéo, d'accès et d'analytics intégrées. Nos systèmes supportent une surveillance 24h/24, des alarmes en temps réel et des preuves claires.",
        benefits: [{ title: "Avantages", items: ["Efficacité améliorée", "Sécurité renforcée", "Gestion unifiée", "Preuves fiables"] }, { title: "Fonctionnalités clés", items: ["Vidéosurveillance HD", "Contrôle d'accès", "Plateforme unifiée", "Support 24h/24"] }],
        features: ["Vidéosurveillance HD", "Contrôle d'accès", "Plateforme unifiée", "Support 24h/24"]
    };
})();
